In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/hackathon_train_set.csv", sep=";")

print("✅ Veri başarıyla ayrıştırıldı!")
print(f"Toplam Ev Sayısı (İlk Hali): {len(df)}")

✅ Veri başarıyla ayrıştırıldı!
Toplam Ev Sayısı (İlk Hali): 27843


In [2]:
selected_columns = [
    'District',
    'Neighborhood',
    'm² (Gross)',
    'm² (Net)',
    'Number of rooms',
    'Building Age',
    'Floor location',
    'Number of floors',
    'Heating',
    'Number of bathrooms',
    'Balcony',
    'Elevator',
    'Furnished',
    'Using status',
    'Available for Loan',
    'Parking Lot',
    'Price'
]

df = df[selected_columns]

In [3]:
df['m2 (Gross)'].unique()

KeyError: 'm2 (Gross)'

In [4]:
df['m² (Gross)'].unique()

array([ 150,   85,  120,  143,  139,  100,  130,  160,   90,  140,  218,
        250,  135,   60,  155,  110,  116,  195,   95,  220,   65,  265,
        340,   83,  125,  105,   82,   88,  115,  104,  260,   80,  200,
        215,   70,  326,  171,   92,  180,  173,  185,   55,  165,  174,
         75,  300,  190,  450,   79,   61,  133,  240,  208,  280,  131,
         97,  145,  154,  148,  210,  132,  350,  128,   87,  286,  113,
         78,   54,  302,   72,  175,   96,   98,  108,   64,   50,   93,
        153,  156,  106,  142,  166,  109,   52,  149,   77,  123,  172,
         81,  164,  170,   40,  102,   84,  178,  241,   67,   86,  147,
        103,   56,  245,  176,  137,  114,   66,  161,  400,  225,  330,
        325,   68,  202,  138,   20,  162,  235,  230,  117,   63,  214,
        197,  198,  146,  430,  194,  107,  506,  189,   42,   53,  270,
        228,  112,  134,  285,  205,  118,  385,  158,  126,  290,  169,
        127,  550,  151,  124,  440,  193,  187,  1

In [6]:
df['m² (Net)'].unique()

array([140.,  80., 100., 124., 115.,  85., 105., 120., 150., 189., 112.,
        90.,  50., 135.,  95.,  83., 110.,  70., 180., 240., 320.,  78.,
        75.,  55.,  88., 220.,  65.,  96., 130., 290., 117., 160., 210.,
        60., 300.,  40., 145., 200., 118.,  48., 280., 182., 450.,  67.,
       170., 113., 190., 201., 158., 125.,  82.,  72., 102.,  92., 330.,
       133.,  77., 215.,  32., 260., 165., 114.,  76., 175.,  56., 250.,
        87.,  68.,  73., 138.,  93., 225.,  41., 230., 126.,  64.,  58.,
       128., 151.,  62.,  84., 185., 122., 103., 108.,  89., 155., 107.,
        66., 154., 164.,  94., 350., 104.,  97., 131.,  98., 197.,  44.,
       315., 380., 153., 144.,  15.,  54.,  45., 129., 123., 335., 214.,
        35.,  47., 285., 136., 183., 188., 420., 162., 134., 169.,  52.,
       217., 177.,  28., 106., 127.,  74., 178.,  39.,  46., 116., 360.,
       310.,  81., 156., 171., 500.,  63., 400.,  59., 270., 245.,  30.,
        79., 132.,  86., 146., 179., 195., 296., 34

In [7]:
df['Number of rooms'].unique()

array(['3+1', '1+1', '2+1', '4+1', '4+2', '3+2', '2+2', '5+1', '6+2',
       '2.5+1', 'Studio (1+0)', '5+4', '3.5+1', '7+2', '4.5+1', '5+2',
       '4+3', '1.5+1', '6+1', '7+1', '2+0', '6+3', '5+3', '8+2', '8+1',
       '4+4', '9+2', '10 and more than', '8+3', '7+3', '10+1', '8+4'],
      dtype=object)

In [8]:
def get_total_rooms(val):
    val = str(val).lower().strip()

    if 'studio' in val:
        return 1.0
    elif '10 and more' in val:
        return 12.0

    try:
        if '+' in val:
            parts = val.split('+')
            return float(parts[0]) + float(parts[1])
    except:
        return np.nan
    return np.nan

df['Number of rooms'] = df['Number of rooms'].apply(get_total_rooms)
    

In [9]:
df['Number of rooms'].unique()

array([ 4. ,  2. ,  3. ,  5. ,  6. ,  8. ,  3.5,  nan,  9. ,  4.5,  5.5,
        7. ,  2.5, 10. , 11. , 12. ])

In [10]:
# 'Number of rooms' sütunu boş (NaN) olan satırları filtrele
nan_satirlar = df[df['Number of rooms'].isna()]

print(nan_satirlar)

        District     Neighborhood  m² (Gross)  m² (Net)  Number of rooms  \
263     Esenyurt    Güzelyurt Mh.          64      56.0              NaN   
347      Sarıyer      Maslak Mah.          52      40.0              NaN   
435     Esenyurt  Turgut Özal Mh.          40      40.0              NaN   
780     Bağcılar      Göztepe Mh.          60      35.0              NaN   
930       Kartal  Kordonboyu Mah.          42      28.0              NaN   
...          ...              ...         ...       ...              ...   
27104  Kağıthane    Talatpaşa Mh.          45      45.0              NaN   
27219   Esenyurt        Pınar Mh.          60      55.0              NaN   
27319   Beşiktaş     Abbasağa Mh.          50      45.0              NaN   
27322     Kartal  Kordonboyu Mah.          36      24.0              NaN   
27639      Tuzla      Aydınlı Mh.          40      29.0              NaN   

       Building Age  Floor location   Number of floors               Heating  \
263    

In [11]:
df['Number of rooms'] = df['Number of rooms'].fillna(1.0)

In [12]:
df['Number of rooms'].unique()

array([ 4. ,  2. ,  3. ,  5. ,  6. ,  8. ,  3.5,  1. ,  9. ,  4.5,  5.5,
        7. ,  2.5, 10. , 11. , 12. ])

In [14]:
df['Building Age'].unique()

array(['26-30 between', '16-20 between', '1', '3', '5-10 between', '2',
       '0', '11-15 between', '4', '31  and more than', '21-25 between'],
      dtype=object)

In [15]:
def conver_age_to_numeric(val):
    val = str(val).lower().strip()

    if 'between' in val:
        clean_val = val.replace('between', '').strip()
        try:
            low, high = clean_val.split('-')
            return (float(low) + float(high)) / 2
        except:
            return np.nan
    elif 'more than' in val:
        return 35.0
    else:
        try:
            return float(val)
        except:
            return np.nan

df['Building Age'] = df['Building Age'].apply(conver_age_to_numeric)

In [16]:
df['Building Age'].unique()

array([28. , 18. ,  1. ,  3. ,  7.5,  2. ,  0. , 13. ,  4. , 35. , 23. ])

In [17]:
print(df.sort_values(by='Building Age'))

         District             Neighborhood  m² (Gross)  m² (Net)  \
16065  Eyüpsultan            Alibeyköy Mh.          90      80.0   
6311        Tuzla              Aydınlı Mh.         140     110.0   
6313        Şişli              Kuştepe Mh.          46      45.0   
6314      Maltepe            İdealtepe Mh.         110      85.0   
16110  Bayrampaşa          Terazidere Mah.         125     115.0   
...           ...                      ...         ...       ...   
27772    Bakırköy  Ataköy 2-5-6. Kısım Mh.          90      90.0   
27803    Bakırköy  Ataköy 2-5-6. Kısım Mh.         115     100.0   
27833       Fatih              Topkapı Mh.         100      90.0   
9872     Beşiktaş          Gayrettepe Mah.          90      80.0   
9883        Şişli          Mecidiyeköy Mh.         100      90.0   

       Number of rooms  Building Age Floor location Number of floors  \
16065              3.0           0.0              3                5   
6311               4.0           0.0   

In [18]:
display(df.head())

District                  Neighborhood  m² (Gross)  m² (Net)  \
0      Güngören  Abdurrahman Nafiz Gürman Mh.         150     140.0   
1      Bağcılar                  100. Yıl Mh.          85      80.0   
2      Ataşehir                     İnönü Mh.         120     100.0   
3  Büyükçekmece               Cumhuriyet Mah.         143     124.0   
4      Çekmeköy               Cumhuriyet Mah.         139     115.0   

   Number of rooms  Building Age Floor location Number of floors  \
0              4.0          28.0              3                3   
1              2.0          18.0   Garden Floor                5   
2              4.0           1.0              5               12   
3              4.0           3.0   Garden Floor                5   
4              4.0           7.5              8                9   

                Heating Number of bathrooms    Balcony  Elevator Furnished  \
0   Natural Gas (Combi)                   1  Available         0        No   
1   Natural Gas (Combi)                   1     Absent         0        No   
2   Natural Gas (Combi)                   2     Absent         1        No   
3    Underfloor heating                   2     Absent         0        No   
4  Center (Share Meter)                   2  Available         1        No   

     Using status Available for Loan  Parking Lot        Price  
0  Property owner                Yes            0   620.000 TL  
1          Tenant                 No            0   115.000 TL  
2            Free                Yes            1   419.000 TL  
3            Free                Yes            0   395.000 TL  
4  Property owner                Yes            1   485.000 TL

In [19]:
df['Floor location'].unique()

array(['3', 'Garden Floor', '5', '8', '4', '1', 'High entrance', '14',
       '6', 'Kot 3', 'Kot 4', '2', '20', 'Kot 1', 'Kot 2', '7',
       'Entrance floor', '9', '11', '27', 'Ground floor', 'Penthouse',
       '18', '13', '12', '15', '25', '10', 'Basement', '17', 'Villa type',
       '24', '30  and more than', '16', '22', '19', '28', '26', '23',
       '21', '29', 'Private'], dtype=object)

In [20]:
def convert_floor_to_numeric(val):
    val = str(val).lower().strip()
    
    # 1. Kot Daireler (Negatif Katlar)
    if 'kot' in val:
        try:
            # "kot 2" -> 2'yi alıp eksi yapıyoruz -> -2
            number = float(val.split()[1])
            return -number
        except:
            return -1.0 # Okunamazsa varsayılan -1
            
    # 2. Bodrum (Basement)
    elif 'basement' in val:
        return -1.0
    
    # 3. Zemin ve Giriş Katlar (0 kabul edilir)
    elif any(x in val for x in ['ground', 'entrance', 'garden', 'villa', 'private']):
        return 0.0
    
    # 4. Yüksek Giriş (Zeminden az daha değerli)
    elif 'high entrance' in val:
        return 0.5
    
    # 5. En Üst Katlar / Penthouse / 30 üzeri
    elif 'penthouse' in val or 'more than' in val:
        return 35.0 # Veri setindeki mantıklı bir tavan değer
    
    # 6. Normal Sayısal Katlar
    else:
        try:
            return float(val)
        except:
            return np.nan

df['Floor location'] = df['Floor location'].apply(convert_floor_to_numeric)

In [21]:
df['Floor location'].unique()

array([ 3.,  0.,  5.,  8.,  4.,  1., 14.,  6., -3., -4.,  2., 20., -1.,
       -2.,  7.,  9., 11., 27., 35., 18., 13., 12., 15., 25., 10., 17.,
       24., 16., 22., 19., 28., 26., 23., 21., 29.])

In [22]:
df['Number of floors'].unique()

array(['3', '5', '12', '9', '4', '6', '8', '17', '11', '14', '24', '10',
       '1', '22', '15', '7', '30  and more than', '13', '2', '16', '18',
       '20', '29', '25', '23', '28', '19', '27', '26', '21'], dtype=object)

In [23]:
def convert_total_floors(val):
    val = str(val).lower().strip()
    
    # "30 and more than" durumu
    if 'more than' in val:
        # 30'dan fazla dediği için ortalama bir gökdelen/rezidans katı olarak 35 veya 40 verebiliriz.
        return 35.0 
    
    # Normal sayılar
    try:
        return float(val)
    except:
        return np.nan

df['Number of floors'] = df['Number of floors'].apply(convert_total_floors)

In [24]:
df['Number of floors'].unique()

array([ 3.,  5., 12.,  9.,  4.,  6.,  8., 17., 11., 14., 24., 10.,  1.,
       22., 15.,  7., 35., 13.,  2., 16., 18., 20., 29., 25., 23., 28.,
       19., 27., 26., 21.])

In [25]:
df['Heating'].unique()

array(['Natural Gas (Combi)', 'Underfloor heating',
       'Center (Share Meter)', 'Central system', 'Naturel gas Stovesı',
       'Absent', 'Floor Heating', 'Stove', 'Climate', 'Fancoil ünitesi',
       'Jeotermal', 'VRV', 'Fancoil Ünitesi', 'Solar energy', 'Fireplace',
       'Heat pump'], dtype=object)

In [26]:
def simplify_heating(val):
    val = str(val).lower().strip()
    
    # 1. Kombi (En yaygın)
    if 'combi' in val:
        return 'Kombi'
    
    # 2. Yerden Isıtma (Değerli bir özellik)
    elif 'floor' in val: # underfloor ve floor heating'i yakalar
        return 'Yerden Isıtma'
    
    # 3. Merkezi Sistemler
    elif 'central' in val or 'center' in val:
        return 'Merkezi Sistem'
    
    # 4. Klima ve Elektrikli modern sistemler
    elif any(x in val for x in ['climate', 'fancoil', 'vrv', 'heat pump']):
        return 'Klima/Elektrikli'
    
    # 5. Soba veya Isıtma Yok (Fiyatı düşüren unsurlar)
    elif 'stove' in val or 'absent' in val or 'fireplace' in val:
        return 'Soba/Yok'
    
    # 6. Diğer (Jeotermal, Solar vb.)
    else:
        return 'Diğer'

df['Simplified heating group'] = df['Heating'].apply(simplify_heating)
print("Temizlenmis Gruplar:")
print(df['Simplified heating group'].value_counts())

Temizlenmis Gruplar:
Simplified heating group
Kombi               21314
Merkezi Sistem       5373
Soba/Yok              534
Yerden Isıtma         507
Klima/Elektrikli      101
Diğer                  14
Name: count, dtype: int64


In [27]:
display(df.head())

District                  Neighborhood  m² (Gross)  m² (Net)  \
0      Güngören  Abdurrahman Nafiz Gürman Mh.         150     140.0   
1      Bağcılar                  100. Yıl Mh.          85      80.0   
2      Ataşehir                     İnönü Mh.         120     100.0   
3  Büyükçekmece               Cumhuriyet Mah.         143     124.0   
4      Çekmeköy               Cumhuriyet Mah.         139     115.0   

   Number of rooms  Building Age  Floor location  Number of floors  \
0              4.0          28.0             3.0               3.0   
1              2.0          18.0             0.0               5.0   
2              4.0           1.0             5.0              12.0   
3              4.0           3.0             0.0               5.0   
4              4.0           7.5             8.0               9.0   

                Heating Number of bathrooms    Balcony  Elevator Furnished  \
0   Natural Gas (Combi)                   1  Available         0        No   
1   Natural Gas (Combi)                   1     Absent         0        No   
2   Natural Gas (Combi)                   2     Absent         1        No   
3    Underfloor heating                   2     Absent         0        No   
4  Center (Share Meter)                   2  Available         1        No   

     Using status Available for Loan  Parking Lot        Price  \
0  Property owner                Yes            0   620.000 TL   
1          Tenant                 No            0   115.000 TL   
2            Free                Yes            1   419.000 TL   
3            Free                Yes            0   395.000 TL   
4  Property owner                Yes            1   485.000 TL   

  Simplified heating group  
0                    Kombi  
1                    Kombi  
2                    Kombi  
3            Yerden Isıtma  
4           Merkezi Sistem

In [28]:
df.drop('Heating', axis=1, inplace=True)

In [29]:
display(df.head())

District                  Neighborhood  m² (Gross)  m² (Net)  \
0      Güngören  Abdurrahman Nafiz Gürman Mh.         150     140.0   
1      Bağcılar                  100. Yıl Mh.          85      80.0   
2      Ataşehir                     İnönü Mh.         120     100.0   
3  Büyükçekmece               Cumhuriyet Mah.         143     124.0   
4      Çekmeköy               Cumhuriyet Mah.         139     115.0   

   Number of rooms  Building Age  Floor location  Number of floors  \
0              4.0          28.0             3.0               3.0   
1              2.0          18.0             0.0               5.0   
2              4.0           1.0             5.0              12.0   
3              4.0           3.0             0.0               5.0   
4              4.0           7.5             8.0               9.0   

  Number of bathrooms    Balcony  Elevator Furnished    Using status  \
0                   1  Available         0        No  Property owner   
1                   1     Absent         0        No          Tenant   
2                   2     Absent         1        No            Free   
3                   2     Absent         0        No            Free   
4                   2  Available         1        No  Property owner   

  Available for Loan  Parking Lot        Price Simplified heating group  
0                Yes            0   620.000 TL                    Kombi  
1                 No            0   115.000 TL                    Kombi  
2                Yes            1   419.000 TL                    Kombi  
3                Yes            0   395.000 TL            Yerden Isıtma  
4                Yes            1   485.000 TL           Merkezi Sistem

In [30]:
df['Number of bathrooms'].unique()

array(['1', '2', '3', '4', 'Absent', '5', '6', '6 and more than'],
      dtype=object)

In [31]:
def clean_bathrooms(val):
    val = str(val).lower().strip()
    
    # 1. "Absent" (Yok) durumu
    if 'absent' in val:
        return 0.0
    
    # 2. "6 ve üzeri" durumu
    elif 'more than' in val:
        return 7.0  # 6'dan büyük en yakın tamsayı
    
    # 3. Normal Sayılar
    try:
        return float(val)
    except:
        return np.nan

df['Number of bathrooms'] = df['Number of bathrooms'].apply(clean_bathrooms)

In [32]:
print(df)

            District                  Neighborhood  m² (Gross)  m² (Net)  \
0           Güngören  Abdurrahman Nafiz Gürman Mh.         150     140.0   
1           Bağcılar                  100. Yıl Mh.          85      80.0   
2           Ataşehir                     İnönü Mh.         120     100.0   
3       Büyükçekmece               Cumhuriyet Mah.         143     124.0   
4           Çekmeköy               Cumhuriyet Mah.         139     115.0   
...              ...                           ...         ...       ...   
27838  Gaziosmanpaşa                   Merkez Mah.          90      80.0   
27839   Küçükçekmece                  Atakent Mah.         156     135.0   
27840     Sancaktepe                     Safa Mah.         170     170.0   
27841      Kağıthane                 Şirintepe Mh.          60      50.0   
27842       Güngören                 Haznedar Mah.         105     100.0   

       Number of rooms  Building Age  Floor location  Number of floors  \
0            

In [33]:
df["Number of bathrooms"].unique()

array([1., 2., 3., 4., 0., 5., 6., 7.])

In [34]:
supheli_evler = df[(df['banyo_sayisi_sayisal'] == 0)]
print(supheli_evler)

KeyError: 'banyo_sayisi_sayisal'

In [35]:
supheli_evler = df[(df['Number of bathrooms'] == 0)]
print(supheli_evler)

            District                Neighborhood  m² (Gross)  m² (Net)  \
480          Esenler                  Fatih Mah.         110     100.0   
797       Bayrampaşa             Kartaltepe Mah.          80      70.0   
1228           Fatih             Silivrikapı Mh.          80      75.0   
1643         Sarıyer                 Ayazağa Mh.         125      84.0   
1843       Kağıthane                Çağlayan Mh.          85      79.0   
2380        Bakırköy               Osmaniye Mah.         150     135.0   
2421      Eyüpsultan            Eyüp Merkez Mah.          85      80.0   
3202     Sultanbeyli        Abdurrahmangazi Mah.          90      85.0   
3238      Bayrampaşa               Yenidoğan Mh.          75      75.0   
4226         Kadıköy              Fenerbahçe Mh.          70      55.0   
4343          Kartal               Çavuşoğlu Mh.          90      85.0   
4346     Sultanbeyli            Mimar Sinan Mah.         125     100.0   
4380           Tuzla                İs

In [36]:
df['Balcony'].unique()

array(['Available', 'Absent', 'Unknown'], dtype=object)

In [37]:
df['Elevator'].unique()

array([0, 1])

In [38]:
df['Furnished'].unique()

array(['No', 'Unknown', 'Yes'], dtype=object)

In [39]:
df['Using status'].unique()

array(['Property owner', 'Tenant', 'Free'], dtype=object)

In [41]:
df['Available for Loan'].unique()

array(['Yes', 'No', 'Unknown'], dtype=object)

In [43]:
df['Parking Lot'].unique()

array([0, 1])

In [44]:
df['Price'].unique()

array([' 620.000 TL', ' 115.000 TL', ' 419.000 TL', ..., ' 1.615.000 TL',
       ' 1.670.000 TL', ' 159.750 TL'], shape=(1876,), dtype=object)

In [47]:
def clean_price(val):
    val = str(val).strip()
    if '...' in val or val == '':
        return np.nan
    # 1. TL, Sterlin, Dolar vb. sembolleri ve harfleri temizle
    val = val.replace('TL', '').replace('tl', '')
    
    # 2. Noktayı (.) tamamen sil (Binlik ayıracı olduğu için)
    # Örnek: 1.615.000 -> 1615000 olur.
    val = val.replace('.', '')
    
    # 3. Virgül (,) varsa ondalıktır, onu noktaya çevir (Nadir ama olabilir)
    val = val.replace(',', '.')
    
    # 4. Boşlukları temizle ve float'a çevir
    try:
        return float(val.strip())
    except:
        return np.nan

df['Price'] = df['Price'].apply(clean_price)

In [46]:
df["Price"].unique()

array([ 620000.,  115000.,  419000., ..., 1615000., 1670000.,  159750.],
      shape=(1484,))

In [48]:
df["Price"].unique()

array([ 6200000.,  1150000.,  4190000., ..., 16150000., 16700000.,
        1597500.], shape=(1484,))

In [51]:
def clean_price(val):
    val = str(val).strip()
   
    # 1. TL, Sterlin, Dolar vb. sembolleri ve harfleri temizle
    val = val.replace('TL', '').replace('tl', '')
    
    # 2. Noktayı (.) tamamen sil (Binlik ayıracı olduğu için)
    # Örnek: 1.615.000 -> 1615000 olur.
    val = val.replace('.', '')
    
    # 3. Virgül (,) varsa ondalıktır, onu noktaya çevir (Nadir ama olabilir)
    val = val.replace(',', '.')
    
    # 4. Boşlukları temizle ve float'a çevir
    try:
        return float(val.strip())
    except:
        return np.nan

df['Price'] = df['Price'].apply(clean_price)

In [54]:
df["Price"].unique()

array([ 620000.,  115000.,  419000., ..., 1615000., 1670000.,  159750.],
      shape=(1484,))

In [53]:
# Tüm fiyatları 1000'e bölerek normale döndür
df['Price'] = df['Price'] / 1000

In [55]:
# 1. Veri tipine bak (float64 yazmalı)
print("Veri Tipi:", df['Price'].dtype)

# 2. İstatistikleri gör (Sadece sayılarda çalışır)
# Ortalama fiyatı, en ucuz ve en pahalı evi gösterir.
print(df['Price'].describe())

Veri Tipi: float64
count    2.784300e+04
mean     7.524979e+05
std      1.463019e+06
min      2.000000e+04
25%      2.780000e+05
50%      4.000000e+05
75%      6.500000e+05
max      4.500000e+07
Name: Price, dtype: float64


In [56]:
df_yedek = pd.read_csv('../data/hackathon_train_set.csv', sep=";")
df['Price'] = df_yedek['Price']


In [57]:
def clean_price(val):
    val = str(val).strip()
   
    # 1. TL, Sterlin, Dolar vb. sembolleri ve harfleri temizle
    val = val.replace('TL', '').replace('tl', '')
    
    # 2. Noktayı (.) tamamen sil (Binlik ayıracı olduğu için)
    # Örnek: 1.615.000 -> 1615000 olur.
    val = val.replace('.', '')
    
    # 3. Virgül (,) varsa ondalıktır, onu noktaya çevir (Nadir ama olabilir)
    val = val.replace(',', '.')
    
    # 4. Boşlukları temizle ve float'a çevir
    try:
        return float(val.strip())
    except:
        return np.nan

df['Price'] = df['Price'].apply(clean_price)

In [58]:
df["Price"].unique()

array([ 620000.,  115000.,  419000., ..., 1615000., 1670000.,  159750.],
      shape=(1484,))

In [59]:
# 1. Veri tipine bak (float64 yazmalı)
print("Veri Tipi:", df['Price'].dtype)

# 2. İstatistikleri gör (Sadece sayılarda çalışır)
# Ortalama fiyatı, en ucuz ve en pahalı evi gösterir.
print(df['Price'].describe())

Veri Tipi: float64
count    2.784300e+04
mean     7.524979e+05
std      1.463019e+06
min      2.000000e+04
25%      2.780000e+05
50%      4.000000e+05
75%      6.500000e+05
max      4.500000e+07
Name: Price, dtype: float64


In [60]:
print(len(df))

27843


In [61]:
display(df.head())

District                  Neighborhood  m² (Gross)  m² (Net)  \
0      Güngören  Abdurrahman Nafiz Gürman Mh.         150     140.0   
1      Bağcılar                  100. Yıl Mh.          85      80.0   
2      Ataşehir                     İnönü Mh.         120     100.0   
3  Büyükçekmece               Cumhuriyet Mah.         143     124.0   
4      Çekmeköy               Cumhuriyet Mah.         139     115.0   

   Number of rooms  Building Age  Floor location  Number of floors  \
0              4.0          28.0             3.0               3.0   
1              2.0          18.0             0.0               5.0   
2              4.0           1.0             5.0              12.0   
3              4.0           3.0             0.0               5.0   
4              4.0           7.5             8.0               9.0   

   Number of bathrooms    Balcony  Elevator Furnished    Using status  \
0                  1.0  Available         0        No  Property owner   
1                  1.0     Absent         0        No          Tenant   
2                  2.0     Absent         1        No            Free   
3                  2.0     Absent         0        No            Free   
4                  2.0  Available         1        No  Property owner   

  Available for Loan  Parking Lot     Price Simplified heating group  
0                Yes            0  620000.0                    Kombi  
1                 No            0  115000.0                    Kombi  
2                Yes            1  419000.0                    Kombi  
3                Yes            0  395000.0            Yerden Isıtma  
4                Yes            1  485000.0           Merkezi Sistem

In [62]:
df['Available for Loan'].unique()

array(['Yes', 'No', 'Unknown'], dtype=object)

In [63]:
df = df[(df['Price'] > 50000) & (df['Price'] < 15000000)]

In [64]:
print(f"Temizlik sonrası satır sayısı: {len(df)}")

Temizlik sonrası satır sayısı: 27783


In [65]:
# Sütun isimlerini İngilizce karakterlere ve alt tireli yapıya çevirelim
df = df.rename(columns={
    'm² (Gross)': 'm2_gross',
    'm² (Net)': 'm2_net',
    'Number of rooms': 'oda_sayisi',
    'Building Age': 'bina_yasi',
    'Floor location': 'bulundugu_kat',
    'Number of floors': 'kat_sayisi',
    'Number of bathrooms': 'banyo_sayisi',
    'Price': 'fiyat',
    'Simplified heating group': 'isitma_tipi',
    'District': 'ilce',
    'Neighborhood': 'mahalle',
    'Furnished': 'esyali_mi',
    'Using status': 'kullanim_durumu',
    'Available for Loan': 'krediye_uygun',
    'Parking Lot': 'otopark',
    'Elevator': 'asansor',
    'Balcony': 'balkon'
})

In [68]:
display(df.head())

ilce                       mahalle  m2_gross  m2_net  oda_sayisi  \
0      Güngören  Abdurrahman Nafiz Gürman Mh.       150   140.0         4.0   
1      Bağcılar                  100. Yıl Mh.        85    80.0         2.0   
2      Ataşehir                     İnönü Mh.       120   100.0         4.0   
3  Büyükçekmece               Cumhuriyet Mah.       143   124.0         4.0   
4      Çekmeköy               Cumhuriyet Mah.       139   115.0         4.0   

   bina_yasi  bulundugu_kat  kat_sayisi  banyo_sayisi  balkon  asansor  \
0       28.0            3.0         3.0           1.0     1.0        0   
1       18.0            0.0         5.0           1.0     0.0        0   
2        1.0            5.0        12.0           2.0     0.0        1   
3        3.0            0.0         5.0           2.0     0.0        0   
4        7.5            8.0         9.0           2.0     1.0        1   

   esyali_mi kullanim_durumu  krediye_uygun  otopark     fiyat     isitma_tipi  
0        0.0  Property owner            1.0        0  620000.0           Kombi  
1        0.0          Tenant            0.0        0  115000.0           Kombi  
2        0.0            Free            1.0        1  419000.0           Kombi  
3        0.0            Free            1.0        0  395000.0   Yerden Isıtma  
4        0.0  Property owner            1.0        1  485000.0  Merkezi Sistem

In [67]:
# Önce string olan 'Yes'/'No' değerlerini map edelim
binary_map = {'Yes': 1, 'No': 0, 'Available': 1, 'Absent': 0}

# Uygulanacak sütunlar
binary_cols = ['esyali_mi', 'krediye_uygun', 'asansor', 'otopark', 'balkon']

for col in binary_cols:
    # Eğer sütun zaten sayısalsa (0, 1 ise) dokunma, değilse map et
    if df[col].dtype == 'object':
        df[col] = df[col].map(binary_map).fillna(0) # Eşleşmeyenleri 0 kabul et

In [69]:
df.drop('mahalle', axis=1, inplace=True)

In [70]:
kategorik_sutunlar = ['ilce', 'kullanim_durumu', 'isitma_tipi']
df = pd.get_dummies(df, columns=kategorik_sutunlar, drop_first=True)

In [71]:
display(df.head())

m2_gross  m2_net  oda_sayisi  bina_yasi  bulundugu_kat  kat_sayisi  \
0       150   140.0         4.0       28.0            3.0         3.0   
1        85    80.0         2.0       18.0            0.0         5.0   
2       120   100.0         4.0        1.0            5.0        12.0   
3       143   124.0         4.0        3.0            0.0         5.0   
4       139   115.0         4.0        7.5            8.0         9.0   

   banyo_sayisi  balkon  asansor  esyali_mi  ...  ilce_Üsküdar  ilce_Şile  \
0           1.0     1.0        0        0.0  ...         False      False   
1           1.0     0.0        0        0.0  ...         False      False   
2           2.0     0.0        1        0.0  ...         False      False   
3           2.0     0.0        0        0.0  ...         False      False   
4           2.0     1.0        1        0.0  ...         False      False   

   ilce_Şişli  kullanim_durumu_Property owner  kullanim_durumu_Tenant  \
0       False                            True                   False   
1       False                           False                    True   
2       False                           False                   False   
3       False                           False                   False   
4       False                            True                   False   

   isitma_tipi_Klima/Elektrikli  isitma_tipi_Kombi  \
0                         False               True   
1                         False               True   
2                         False               True   
3                         False              False   
4                         False              False   

   isitma_tipi_Merkezi Sistem  isitma_tipi_Soba/Yok  isitma_tipi_Yerden Isıtma  
0                       False                 False                      False  
1                       False                 False                      False  
2                       False                 False                      False  
3                       False                 False                       True  
4                        True                 False                      False  

[5 rows x 58 columns]

In [72]:
print(df.head())
print(df.info()) # Dtype'ların hepsi int veya float olmalı

   m2_gross  m2_net  oda_sayisi  bina_yasi  bulundugu_kat  kat_sayisi  \
0       150   140.0         4.0       28.0            3.0         3.0   
1        85    80.0         2.0       18.0            0.0         5.0   
2       120   100.0         4.0        1.0            5.0        12.0   
3       143   124.0         4.0        3.0            0.0         5.0   
4       139   115.0         4.0        7.5            8.0         9.0   

   banyo_sayisi  balkon  asansor  esyali_mi  ...  ilce_Üsküdar  ilce_Şile  \
0           1.0     1.0        0        0.0  ...         False      False   
1           1.0     0.0        0        0.0  ...         False      False   
2           2.0     0.0        1        0.0  ...         False      False   
3           2.0     0.0        0        0.0  ...         False      False   
4           2.0     1.0        1        0.0  ...         False      False   

   ilce_Şişli  kullanim_durumu_Property owner  kullanim_durumu_Tenant  \
0       False            

In [73]:
df.dropna(subset=['m2_net'], inplace=True)

In [74]:
bool_sutunlar = df.select_dtypes(include=['bool']).columns
df[bool_sutunlar] = df[bool_sutunlar].astype(int)

In [75]:
print(df.info()) # Dtype'ların hepsi int veya float olmalı

<class 'pandas.core.frame.DataFrame'>
Index: 27762 entries, 0 to 27842
Data columns (total 58 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   m2_gross                        27762 non-null  int64  
 1   m2_net                          27762 non-null  float64
 2   oda_sayisi                      27762 non-null  float64
 3   bina_yasi                       27762 non-null  float64
 4   bulundugu_kat                   27762 non-null  float64
 5   kat_sayisi                      27762 non-null  float64
 6   banyo_sayisi                    27762 non-null  float64
 7   balkon                          27762 non-null  float64
 8   asansor                         27762 non-null  int64  
 9   esyali_mi                       27762 non-null  float64
 10  krediye_uygun                   27762 non-null  float64
 11  otopark                         27762 non-null  int64  
 12  fiyat                           27762

In [76]:
df.to_csv('cleaned_data_set.csv', index=False)

In [78]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

X = df.drop('fiyat', axis=1)
y = df['fiyat']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Model {len(X_train)} ev ile egitilecek, {len(X_test)} ev ile test edilecek.")

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)


Model 22209 ev ile egitilecek, 5553 ev ile test edilecek.


In [79]:
print("Model eğitiliyor... (Bu işlem bilgisayar hızına göre 1-2 dakika sürebilir)")
rf_model.fit(X_train, y_train)

Model eğitiliyor... (Bu işlem bilgisayar hızına göre 1-2 dakika sürebilir)


RandomForestRegressor(random_state=42)

In [80]:
y_pred = rf_model.predict(X_test)

r2 = r2_score(y_test, y_pred)
print("-" * 30)
print(f"Model Basarisi (R2 Skoru): {r2:.2f}")
print("-" * 30)

------------------------------
Model Basarisi (R2 Skoru): 0.77
------------------------------


In [81]:
import matplotlib.pyplot as plt
import seaborn as sns

# Özelliklerin önem derecelerini al
onem_dereceleri = pd.DataFrame({
    'Ozellik': X_train.columns,
    'Onem': rf_model.feature_importances_
})

# Puana göre sırala (En önemli en üstte)
onem_dereceleri = onem_dereceleri.sort_values(by='Onem', ascending=False).head(20)

# Grafik Çiz
plt.figure(figsize=(12, 8))
sns.barplot(x='Onem', y='Ozellik', data=onem_dereceleri, palette='viridis')
plt.title('Evin Fiyatını Belirleyen En Önemli 20 Faktör')
plt.xlabel('Önem Derecesi')
plt.ylabel('Özellikler')
plt.show()

ModuleNotFoundError: No module named 'seaborn'

In [83]:
import joblib

# 1. Modeli kaydet
joblib.dump(rf_model, '../models/istanbul_ev_fiyat_modeli.pkl')

print("Model başarıyla kaydedildi! Artık tekrar eğitmene gerek yok.")

Model başarıyla kaydedildi! Artık tekrar eğitmene gerek yok.


In [84]:
X_test.sample(5)
tahminler = rf_model.predict(ornekler)

karsilastirma = pd.DataFrame({
    'Gercek Fiyat': y_test.loc[ornekler.index],
    'Tahmin Edilen': tahminler,
    'Fark (TL)': y_test.loc[ornekler.index] - tahminler
    )}

pd.options.display.float_format = '{:,.0f}'.format
print(karsilastirma)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '{' on line 4 (397920395.py, line 8)

In [85]:
# Rastgele 5 ev seç ve karşılaştır
ornekler = X_test.sample(5)
tahminler = rf_model.predict(ornekler)

# Sonuçları yan yana görelim
karsilastirma = pd.DataFrame({
    'Gerçek Fiyat': y_test.loc[ornekler.index],
    'Tahmin Edilen': tahminler,
    'Fark (TL)': y_test.loc[ornekler.index] - tahminler
})

# Okuması kolay olsun diye formatlayalım
pd.options.display.float_format = '{:,.0f}'.format
print(karsilastirma)

       Gerçek Fiyat  Tahmin Edilen  Fark (TL)
4008      2,500,000      1,134,350  1,365,650
25122       230,000        247,313    -17,313
17951       390,000        318,400     71,600
14765       550,000        546,080      3,920
18728       300,000        380,940    -80,940


In [86]:
import joblib

# 1. Modeli diskten yükle
model_2 = joblib.load('../models/house_price_model.pkl')

# 2. AYNI test setiyle tahmin yaptır
# (Dikkat: Yüklediğin model de aynı sütun sırasını bekler!)
y_pred_2 = model_2.predict(X_test)

# 3. Skoru hesapla
print(f"Yüklenen Modelin Skoru: {r2_score(y_test, y_pred_2):.4f}")

ValueError: columns are missing: {'District', 'Neighborhood_Avg_Price', 'Neighborhood', 'Floor location', 'Number of rooms', 'Building Age', 'm² (Net)'}

In [87]:
from sklearn.model_selection import GridSearchCV

# 1. Denenecek ayarların listesi (Menü)
parametre_gridi = {
    'n_estimators': [100, 200, 300],        # Ağaç sayısı seçenekleri
    'max_depth': [None, 10, 20, 30],        # Derinlik seçenekleri
    'min_samples_split': [2, 5, 10],        # Bölünme kuralı
    'min_samples_leaf': [1, 2, 4]           # Yaprak kuralı
}

# 2. Modeli ve GridSearch'ü hazırla
rf = RandomForestRegressor(random_state=42)

# cv=3: Veriyi 3 parçaya bölüp çapraz doğrulama yapar (Sağlamasını yapar)
grid_search = GridSearchCV(estimator=rf, param_grid=parametre_gridi, 
                           cv=3, n_jobs=-1, verbose=2)

print("En iyi ayarlar aranıyor... Kahveni al bekle ☕")
grid_search.fit(X_train, y_train)

# 3. Sonuçları Göster
print("\nEn İyi Ayarlar:", grid_search.best_params_)

# 4. En iyi ayarlarla skoru tekrar ölç
best_model = grid_search.best_estimator_
y_pred_new = best_model.predict(X_test)
print(f"Yeni R2 Skoru: {r2_score(y_test, y_pred_new):.4f}")

En iyi ayarlar aranıyor... Kahveni al bekle ☕
Fitting 3 folds for each of 108 candidates, totalling 324 fits

En İyi Ayarlar: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 200}
Yeni R2 Skoru: 0.7684


In [88]:
# Gerekli kütüphaneler
from sklearn.ensemble import VotingRegressor, RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import xgboost as xgb # XGBoost kütüphanesi

# 1. TAKIM OYUNCULARINI SEÇELİM
# Random Forest (Genel kaptan)
rf = RandomForestRegressor(n_estimators=200, random_state=42)

# XGBoost (Hata avcısı - Kaggle şampiyonu)
xgb_model = xgb.XGBRegressor(n_estimators=1000, learning_rate=0.05, n_jobs=-1, random_state=42)

# Linear Regression (Basit ilişkileri garantiye alan sigorta)
lr = LinearRegression()

# 2. SÜPER MODELİ (VOTING) KURUYORUZ
# weights=[1, 2, 1]: XGBoost'un sözü 2 kat değerli olsun dedik.
voting_model = VotingRegressor(
    estimators=[('rf', rf), ('xgb', xgb_model), ('lr', lr)],
    weights=[1, 2, 1] 
)

print("🚀 Süper Model eğitiliyor... (Biraz sürebilir)")
voting_model.fit(X_train, y_train)

# 3. TEST ZAMANI
y_pred_vote = voting_model.predict(X_test)

# Skoru Yazdır
print("-" * 40)
print(f"Süper Model (Voting) R2 Skoru: {r2_score(y_test, y_pred_vote):.4f}")
print("-" * 40)

🚀 Süper Model eğitiliyor... (Biraz sürebilir)
----------------------------------------
Süper Model (Voting) R2 Skoru: 0.7633
----------------------------------------


In [89]:
import xgboost as xgb
from sklearn.metrics import r2_score

# XGBoost'u tek başına, güçlü ayarlarla kuralım
# n_estimators=1000: Çok sayıda ağaç
# learning_rate=0.05: Yavaş ve sindirerek öğren (Daha hassas)
xgb_final = xgb.XGBRegressor(
    n_estimators=2000, 
    learning_rate=0.03, 
    max_depth=6, 
    colsample_bytree=0.8,
    n_jobs=-1, 
    random_state=42
)

print("XGBoost tek başına eğitiliyor... 🌪️")
xgb_final.fit(X_train, y_train)

# Test et
y_pred_xgb = xgb_final.predict(X_test)
print(f"XGBoost Final Skoru: {r2_score(y_test, y_pred_xgb):.4f}")

XGBoost tek başına eğitiliyor... 🌪️
XGBoost Final Skoru: 0.7586
[CV] END max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=  17.8s
[CV] END max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  15.4s
[CV] END max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  16.0s
[CV] END max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=300; total time=  49.5s
[CV] END max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=  15.8s
[CV] END max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=200; total time=  33.1s
[CV] END max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=  35.6s
[CV] END max_depth=None, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=  29.7s
[CV] END max_depth=None, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=  14.6s
[CV] END

In [90]:
import pandas as pd
import os
import joblib
from sklearn.ensemble import RandomForestRegressor

# 1. ŞAMPİYON MODELİ EĞİT (En iyi ayarlar: Varsayılanlar)
print("🏆 Şampiyon Model (Random Forest) son kez eğitiliyor...")
final_model = RandomForestRegressor(n_estimators=100, random_state=42)
final_model.fit(X_train, y_train)

# 2. GÜVENLİ KAYIT (Klasör yoksa oluşturur)
klasor_yolu = '../models/'  # Proje klasörünün içine kaydeder
os.makedirs(klasor_yolu, exist_ok=True)
dosya_yolu = os.path.join(klasor_yolu, 'house_price_model.pkl')

joblib.dump(final_model, dosya_yolu)
print(f"✅ Model başarıyla kaydedildi: {dosya_yolu}")

# 3. KULLANIM FONKSİYONU (Bunu kopyalayıp saklayabilirsin)
def fiyat_sor(ozellikler):
    # Veriyi hazırla
    df_yeni = pd.DataFrame([ozellikler])
    df_yeni = pd.get_dummies(df_yeni)
    # Eğitimdeki sütunlarla eşitle (Eksikleri 0 yap)
    df_yeni = df_yeni.reindex(columns=X_train.columns, fill_value=0)
    # Tahmin
    tahmin = final_model.predict(df_yeni)
    return tahmin[0]

print("\n🎉 Tebrikler! Yapay Zeka projen tamamlandı.")
print("Artık 'fiyat_sor(benim_evim)' fonksiyonunu kullanarak istediğin evi fiyatlayabilirsin.")

🏆 Şampiyon Model (Random Forest) son kez eğitiliyor...
✅ Model başarıyla kaydedildi: ../models/house_price_model.pkl

🎉 Tebrikler! Yapay Zeka projen tamamlandı.
Artık 'fiyat_sor(benim_evim)' fonksiyonunu kullanarak istediğin evi fiyatlayabilirsin.


In [91]:
from sklearn.metrics import r2_score, mean_absolute_error
import pandas as pd
import numpy as np

# 1. Tahminleri Al
y_pred_final = final_model.predict(X_test)

# 2. Metrikleri Hesapla
r2 = r2_score(y_test, y_pred_final)
mae = mean_absolute_error(y_test, y_pred_final)

print("📊 FINAL MODEL KARNESİ")
print("-" * 30)
print(f"🏆 R2 Başarı Skoru    : %{r2*100:.2f}") 
print(f"💰 Ortalama Sapma (Hata): {mae:,.0f} TL")
print("-" * 30)

# 3. Gözle Kontrol (Rastgele 10 Ev)
# Gerçek ve Tahmini yan yana koyup farka bakalım
sonuc_tablosu = pd.DataFrame({
    'Gerçek Fiyat': y_test,
    'Yapay Zeka Tahmini': y_pred_final,
    'Fark (Hata)': np.abs(y_test - y_pred_final)
})

# Rastgele 10 tanesini göster
print("\n🏠 Örnek 10 Ev Tahmini:")
print(sonuc_tablosu.sample(10))

📊 FINAL MODEL KARNESİ
------------------------------
🏆 R2 Başarı Skoru    : %76.68
💰 Ortalama Sapma (Hata): 204,867 TL
------------------------------

🏠 Örnek 10 Ev Tahmini:
       Gerçek Fiyat  Yapay Zeka Tahmini  Fark (Hata)
16710       630,000             633,520        3,520
26125       179,000             147,080       31,920
1419        350,000             333,540       16,460
14915     1,120,000           1,447,495      327,495
7723        238,000             231,310        6,690
11979       800,000           1,010,920      210,920
6631        357,500             388,390       30,890
17574       440,000             365,720       74,280
21272       450,000             382,235       67,765
964       1,350,000             364,463      985,537
